# 1.python基础试题

1.1 python 中boolean、float 和 int 分别表示什么？

In [ ]:
boolean：布尔值，用于判断真假，True为真，False为假
float：浮点数
int：整数

1.2  设计求1-2+3-4+5 ... 99的所有数的和

In [1]:
a=0
for i in range(1,100):
    if(i % 2 == 0):
        a = a - i
    else:
        a = a + i
print(a)
        

50


1.3  将字符串 s="yoyo" 转换成列表

In [2]:
l = []
s = "yoyo"
for i in s:
    l.append(i)
print(l)

['y', 'o', 'y', 'o']


# 2. python进阶基础试题

2.1     for i in range(1,100)[2::3][-10:]: 

                print i 
                
        理解这段代码，并说出它是如何取数的

In [3]:
for i in range(1,100)[2::3][-10:]:
            print(i)
#先从1到100中取出3的倍数的数，再从这些数中取出后面10个数字

72
75
78
81
84
87
90
93
96
99


2.2 使用init 实例化时自动运行  分别计算单只股票最高价和收盘价两个时间点差值问题,可统一为one、two两个时间点,其最高价和收盘价赋值为 one(15,7) two(66,20)

In [4]:
class stock:
    def __init__(self,time, close, high):
        self.time=time
        self.close = close
        self.high = high
    def calAmount(self):
        return {self.time+'_diff': self.close-self.high}
one = stock('one', 15, 7)
print(one.calAmount())

two = stock('two', 66, 20)
print(two.calAmount())

{'one_diff': 8}
{'two_diff': 46}


# 3. pandas数据处理试题

3.1 如何查看列名、怎么对数据转置

In [6]:
'''
查看列名：
假设data是一个dataframe
则data.columns.values 返回列名的 array
'''

#数据转置
import numpy as np
arr = np.arange(16).reshape(4, 4)
print(arr)
arr2 = arr.transpose((1,0))
print(arr2)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 0  4  8 12]
 [ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]]


3.2 读取data里的600029这只股票的DataFrame,将其收盘价转换成用Numpy的Array格式，并用talib计算10日EMA值，返回ndarray的最后五个值

In [7]:
import numpy as np
import pandas as pd
import talib as ta
import warnings
warnings.filterwarnings('ignore')

stock = pd.read_excel('sz50.xlsx',sheetname='600029.XSHG', index_col='datetime')
print(ta.MA(stock.close.values, 1))

[ 11.64  11.72  11.8   11.8   11.85  12.73  12.13  11.98  11.97  12.02
  11.97  12.03  11.98  12.03  12.17  12.18  12.22  12.08  12.03  11.89
  11.89  11.95  11.98  12.15  12.2   12.18  12.3   12.48  12.3   12.68
  12.76  12.79  12.61  13.07  12.69  12.71  12.86  12.76  12.74  12.88
  12.78  12.73  12.69  12.76  12.83  12.91  13.09  13.16  12.96  12.81
  12.79  13.01  13.09  13.52  13.54  13.32  13.47  13.49  13.62  13.77
  13.95  13.67  13.63  13.45  13.49  13.39  13.27  13.32  13.44  13.32
  13.01  12.61  12.78  12.71  12.84  12.96  12.86  13.06  13.21  13.19
  13.06  13.29  13.5   13.49  13.52  13.35  13.35  13.21  13.35  13.5
  13.52  13.73  14.03  14.25  14.53  14.31  14.38  14.46  14.38  14.76
  14.89  14.99  14.82  14.59  14.67  14.67  14.99  14.74  14.76  14.82
  14.63  14.94  14.53  14.25  14.3   14.36  14.21  14.2   14.28  14.26
  14.16  13.82  13.83  13.7   13.9   14.11  14.1   14.18  14.25  14.08
  14.13  14.1   13.72  13.17  13.27  13.22  13.29  13.44  13.37  13.14
  13.16

In [8]:
print(ta.EMA(stock.close.values, 10)[-5:])

[ 15.08227205  15.2564044   15.44433088  15.72172526  15.96322976]


3.3 读取sz50.xlsx的['600029.XSHG','600050.XSHG','601318.XSHG']的全数据做成Panel

In [9]:
from datetime import datetime
import pandas as pd
symbol=['600029.XSHG','600050.XSHG','601318.XSHG']
data_dict = {}
for s in symbol:
    data =  pd.read_excel('sz50.xlsx',sheetname=s, index_col='datetime')
    data_dict[s] = data.loc['2017-01-03':'2017-11-20']
PN = pd.Panel(data_dict)
print(PN)

<class 'pandas.core.panel.Panel'>
Dimensions: 3 (items) x 215 (major_axis) x 5 (minor_axis)
Items axis: 600029.XSHG to 601318.XSHG
Major_axis axis: 2017-01-03 15:00:00 to 2017-11-20 15:00:00
Minor_axis axis: close to volume


3.4把Panel转成ndim为3的Numpy，然后用array的切片读取ndim为2的三只股票最近20天的收盘价

In [10]:
 MI = PN.to_frame()
MI_tp = PN.transpose(2,1,0)
MI_tp = PN.transpose(2,1,0).to_frame()
print(MI_tp)

                                  close    high     low    open       volume
datetime            minor                                                   
2017-01-03 15:00:00 600029.XSHG   11.64   11.69   11.54   11.55   26749400.0
                    600050.XSHG    8.99    9.14    8.73    8.76  242291182.0
                    601318.XSHG   79.89   80.65   79.11   79.15   29687099.0
2017-01-04 15:00:00 600029.XSHG   11.72   11.75   11.55   11.62   45710506.0
                    600050.XSHG    8.98    9.04    8.82    8.95  200960890.0
                    601318.XSHG   79.87   80.16   79.53   79.94   25257305.0
2017-01-05 15:00:00 600029.XSHG   11.80   11.93   11.77   11.82   56905338.0
                    600050.XSHG    9.48    9.50    8.91    8.93  360200783.0
                    601318.XSHG   80.02   80.50   79.91   80.02   28689533.0
2017-01-06 15:00:00 600029.XSHG   11.80   11.92   11.77   11.82   42445959.0
                    600050.XSHG    9.27    9.51    9.21    9.37  281319845.0

In [11]:
s1 = MI_tp.close.values[0::3][-20:]
s2 = MI_tp.close.values[1::3][-20:]
s3 = MI_tp.close.values[2::3][-20:]
print(s2)
print(s3)
print(s1)

[ 13.85  13.82  13.83  14.11  14.25  14.39  15.1   15.15  15.22  14.97
  14.89  14.99  14.71  15.07  15.35  16.    16.04  16.29  16.97  17.05]
[ 8.53  8.56  8.62  8.88  9.25  9.24  9.43  9.25  9.02  9.15  9.63  9.5
  9.9   9.97  9.96  9.49  9.68  9.61  9.63  9.8 ]
[ 134.83  134.56  137.5   143.18  143.48  144.15  143.61  143.65  144.35
  143.36  146.41  144.71  148.56  156.53  157.12  157.72  154.99  163.52
  168.58  169.57]


3.5 建立一个5*5的矩阵，值从0到24

In [12]:
import numpy as np
s = np.arange(25).reshape(5,5)
print(s)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
